# Generated by Django 5.2 on 2026-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upgrade_check", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="version",
            constraint=models.CheckConstraint(
                condition=models.Q(("version", ""), _negated=True),
                name="non_empty_version",
            ),
        ),
    ]
